service: reacjilator

provider:
  name: aws
  region: ap-northeast-1
  runtime: java8
  stage: ${opt:stage, 'dev'}
  # To warmup lambda functions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
  environment:
    SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    GOOGLE_APPLICATION_CREDENTIALS: ${env:GOOGLE_APPLICATION_CREDENTIALS}
    SERVERLESS_STAGE: ${opt:stage, 'dev'}

package:
  artifact: target/scala-2.12/reacjilator.jar

plugins:
  # Enable to export the settings managed by serverless as SAM template.yml
  - serverless-sam

functions:
  echo:
    handler: slackapp.handler.EchoHandler
    events:
      - http:
          path: echo
          method: get

  events:
    handler: slackapp.handler.SlackEventsHandler
    timeout: 30
    events:
      - http:
          path: slack/events
          method: post

  warmup:
    handler: slackapp.handler.WarmupHandler
    timeout: 120 # optional, in seconds, default is 6
    events:
      - schedule: rate(5 minutes)
